#!/bin/bash -e
# Tests the results of manually swapping columns of 10 files in LibreOffice CALC.
# USAGE: ./colswaptests_batch_run
# To add more tests: manually swap cols in a csv using LibreOffice and write the tester, copying the structure of the existing testers. 
# Hand write the desired output into the tester. Then add an appropriate line to this script, of the form:
#
# ./tests/testerk
#
# This will work when run from any directory on this machine (Menasheh).
# NOTE: to run testers individually, run them from ~/Saimoukh/Lemmy/Testing\ colswaps/csv_testing


# TEST DESCRIPTIONS:
# 1. test1 tests whether the col swapper works when an empty first col (1) is swapped with an occupied last col (3). (n, m) = (1, 3)2. tester2 tests whether the col swapper 
#    works when an empty last col (3) is swapped with an occupied middle col (2). (n, m) = (2, 3)
# 3. test3 tests whether the colswap program works when an empty middle column (2) is swapped with an occupied last column (3). (n, m) = (2, 3)
# 4. test4 tests whether the colswap program can handle escaped commas. 
# 5. test5 tests whether the col swapper works when some of the rows have fewer fields than others, as long as the swap is done on cols that are defined for each row. 
# 6. test6 tests whether the col swapper not only swaps the desired columns but still writes the other columns. 
# 7. test7 tests whether swapper works when 1st and last col are empty
# 8. test8 tests whether swapper works when all cols are empty
# 9. test9 tests whether swapper works when you are swapping two adjacent cols
# 10. test10 tests whether swapper works when you are swapping two middle cols




cd ~/Saimoukh/Lemmy/Testing\ colswaps/csv_testing
./tests/tester1
./tests/tester2
./tests/tester3
./tests/tester4
./tests/tester5
./tests/tester6
./tests/tester7
./tests/tester8
./tests/tester9
./tests/tester10


