#!/bin/bash
# Tests whether the colswap program works when an empty column 2 is swapped with an occupied column 3.

s1='texture,disposition,size
furry,guy,
fluffy,beast,
destructive,animal,'
s2=$(cat ./outputs/output3.csv)

# printf "$s2\n"
# printf "$s1\n"

if [ "$s1" == "$s2" ];
then
	echo 1 test3 swaps empty middle col and occupied \last col.
else
	echo 0 test3 swaps empty middle col and occupied \last col.
fi
