#!/bin/bash
# test10 tests whether swapper works when you are swapping two middle cols.

s1='ownership,size,status,texture,disposition
my,little,cute,furry,guy
my,little,cute,fluffy,beast
my,little,cute,destructive,animal'

s2=$(cat ./outputs/output10.csv)

# printf "$s2\n"
# printf "$s1\n"

if [ "$s1" == "$s2" ];
then
	echo 1 test10 tests whether swapper works when you are swapping two middle cols.
else
	echo 0 test10 tests whether swapper works when you are swapping two middle cols.
fi
