#!/bin/bash
# Tests whether the col swapper not only swaps the desired columns but still writes the other columns. 

cd ..
sqlite3 -csv inputs.db 'select texture,disposition,size,status from input6;' > ~/Saimoukh/sqlite_colswaps/outputs/output6

s1='furry,guy,little,he is
fluffy,beast,little,I say
destructive,animal,little,she is'

s2=$(cat ~/Saimoukh/sqlite_colswaps/outputs/output6)

if [ "$s1" == "$s2" ];
then
	echo 1 test6 tests whether the col swapper not only swaps the desired columns but still writes the other columns.
else
	echo 0 test6 tests whether the col swapper not only swaps the desired columns but still writes the other columns. 
fi
