#!/bin/bash
# Tests whether the col swapper can handle escaped commas.

cd ..
sqlite3 -csv inputs.db 'select texture,disposition,size from input4;' > ~/Saimoukh/sqlite_colswaps/outputs/output4

s1='furry,guy,cute\,little
fluffy,beast,little
destructive,animal,little'

s2=$(cat ~/Saimoukh/sqlite_colswaps/outputs/output4)

if [ "$s1" == "$s2" ];
then
	echo 1 test4 tests whether swapper can handle escaped commas.
else
	echo 0 test4 tests whether swapper can handle escaped commas.
fi
