#!/bin/bash
# test9 tests whether swapper works when you're swapping two adjacent cols. 

cd ..
sqlite3 -csv inputs.db 'select ownership,texture,status,size,disposition from input9;' > ~/Saimoukh/sqlite_colswaps/outputs/output9

s1='my,furry,cute,little,guy
my,fluffy,cute,little,beast
my,destructive,cute,little,animal'

s2=$(cat ~/Saimoukh/sqlite_colswaps/outputs/output9)

if [ "$s1" == "$s2" ];
then
	echo 1 test9 tests whether swapper works when you are swapping two adjacent cols.
else
	echo 0 test9 tests whether swapper works when you are swapping two adjacent cols.
fi
